create template for Policy.sh from Policy_sh.SH
Signed-off-by: Thomas E. Dickey <dickey@invisible-island.net>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9637,223 +9637,395 @@ fi
 
 ###############################################################################
 
-cat >>confdefs.h <<\EOF
+	cat >>confdefs.h <<\EOF
+#define PRIVBIN "/usr/lib/trn4"
+EOF
+
+	PRIVBIN=""/usr/lib/trn4""
+
+	cat >>confdefs.h <<\EOF
+#define PRIVLIB "/usr/share/trn4"
+EOF
+
+	PRIVLIB=""/usr/share/trn4""
+
+	cat >>confdefs.h <<\EOF
+#define ispell_prg "/usr/bin/ispell"
+EOF
+
+	ispell_prg=""/usr/bin/ispell""
+
+	cat >>confdefs.h <<\EOF
+#define ispell_options ""
+EOF
+
+	ispell_options=""""
+
+	cat >>confdefs.h <<\EOF
+#define useinews "/usr/lib/trn4/inews"
+EOF
+
+	useinews=""/usr/lib/trn4/inews""
+
+	cat >>confdefs.h <<\EOF
 #define ACTIVE "remote"
 EOF
 
-cat >>confdefs.h <<\EOF
+	ACTIVE=""remote""
+
+	cat >>confdefs.h <<\EOF
 #define ACTIVE_TIMES "remote"
 EOF
 
-cat >>confdefs.h <<\EOF
+	ACTIVE_TIMES=""remote""
+
+	cat >>confdefs.h <<\EOF
 #define BERKNAMES 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	BERKNAMES=1
+
+	cat >>confdefs.h <<\EOF
 #define CALL_INEWS "/usr/lib/trn4/inews -h <%h"
 EOF
 
-cat >>confdefs.h <<\EOF
+	CALL_INEWS=""/usr/lib/trn4/inews -h <%h""
+
+	cat >>confdefs.h <<\EOF
 #define DEFEDITOR "/usr/bin/editor"
 EOF
 
-cat >>confdefs.h <<\EOF
+	DEFEDITOR=""/usr/bin/editor""
+
+	cat >>confdefs.h <<\EOF
 #define Direntry_t struct dirent
 EOF
 
-cat >>confdefs.h <<\EOF
+	Direntry_t="struct dirent"
+
+	cat >>confdefs.h <<\EOF
 #define EXTRAINEWS "/usr/bin/inews"
 EOF
 
-cat >>confdefs.h <<\EOF
+	EXTRAINEWS=""/usr/bin/inews""
+
+	cat >>confdefs.h <<\EOF
 #define GROUPDESC ""
 EOF
 
-cat >>confdefs.h <<\EOF
+	GROUPDESC=""""
+
+	cat >>confdefs.h <<\EOF
 #define HASATTRIBUTE 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	HASATTRIBUTE=1
+
+	cat >>confdefs.h <<\EOF
 #define HAVE_LOCAL_SPOOL 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	HAVE_LOCAL_SPOOL=1
+
+	cat >>confdefs.h <<\EOF
 #define HAVE_TERMLIB 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	HAVE_TERMLIB=1
+
+	cat >>confdefs.h <<\EOF
 #define HOSTBITS 2
 EOF
 
-cat >>confdefs.h <<\EOF
+	HOSTBITS=2
+
+	cat >>confdefs.h <<\EOF
 #define INSTALLPREFIX "/usr"
 EOF
 
-cat >>confdefs.h <<\EOF
+	INSTALLPREFIX=""/usr""
+
+	cat >>confdefs.h <<\EOF
 #define INTERNET 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	INTERNET=1
+
+	cat >>confdefs.h <<\EOF
 #define I_DIRENT 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_DIRENT=1
+
+	cat >>confdefs.h <<\EOF
 #define I_STDLIB 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_STDLIB=1
+
+	cat >>confdefs.h <<\EOF
 #define I_STRING 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_STRING=1
+
+	cat >>confdefs.h <<\EOF
 #define I_SYS_DIR 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_SYS_DIR=1
+
+	cat >>confdefs.h <<\EOF
 #define I_SYS_IOCTL /**/
 EOF
 
-cat >>confdefs.h <<\EOF
+	cat >>confdefs.h <<\EOF
 #define I_SYS_TIME 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_SYS_TIME=1
+
+	cat >>confdefs.h <<\EOF
 #define I_SYS_WAIT 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_SYS_WAIT=1
+
+	cat >>confdefs.h <<\EOF
 #define I_TERMIOS 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_TERMIOS=1
+
+	cat >>confdefs.h <<\EOF
 #define I_TIME 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_TIME=1
+
+	cat >>confdefs.h <<\EOF
 #define I_UNISTD 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_UNISTD=1
+
+	cat >>confdefs.h <<\EOF
 #define I_UTIME 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	I_UTIME=1
+
+	cat >>confdefs.h <<\EOF
 #define MAILFILE "/var/mail/%L"
 EOF
 
-cat >>confdefs.h <<\EOF
+	MAILFILE=""/var/mail/%L""
+
+	cat >>confdefs.h <<\EOF
 #define MAILPOSTER "/usr/lib/trn4/Rnmail -h %h"
 EOF
+
+	MAILPOSTER=""/usr/lib/trn4/Rnmail -h %h""
 
 cat >>confdefs.h <<\EOF
 #define MBOXCHAR 'F'
 EOF
 
-cat >>confdefs.h <<\EOF
+	cat >>confdefs.h <<\EOF
 #define MIMECAP "%./.mimecap:~/.mailcap:/etc/mailcap"
 EOF
 
-cat >>confdefs.h <<\EOF
+	MIMECAP=""%./.mimecap:~/.mailcap:/etc/mailcap""
+
+	cat >>confdefs.h <<\EOF
 #define NEWSLIB "/var/lib/news"
 EOF
 
-cat >>confdefs.h <<\EOF
+	NEWSLIB=""/var/lib/news""
+
+	cat >>confdefs.h <<\EOF
 #define NEWSPOSTER "/usr/lib/trn4/Pnews -h %h"
 EOF
 
-cat >>confdefs.h <<\EOF
+	NEWSPOSTER=""/usr/lib/trn4/Pnews -h %h""
+
+	cat >>confdefs.h <<\EOF
 #define NEWSSPOOL "none"
 EOF
 
-cat >>confdefs.h <<\EOF
+	NEWSSPOOL=""none""
+
+	cat >>confdefs.h <<\EOF
 #define NEWS_ADMIN "news"
 EOF
 
-cat >>confdefs.h <<\EOF
+	NEWS_ADMIN=""news""
+
+	cat >>confdefs.h <<\EOF
 #define NORMSIG 1
 EOF
 
-cat >>confdefs.h <<\EOF
+	NORMSIG=1
+
+	cat >>confdefs.h <<\EOF
 #define ORGNAME "/etc/news/organization"
 EOF
 
-cat >>confdefs.h <<\EOF
-#define OVERVIEW_DIR "remote"
-EOF
+	ORGNAME=""/etc/news/organization""
 
-cat >>confdefs.h <<\EOF
-#define OVERVIEW_FMT "none"
-EOF
-
-cat >>confdefs.h <<\EOF
-#define PASSNAMES 1
-EOF
-
-cat >>confdefs.h <<\EOF
-#define PHOSTCMD "/usr/bin/hostname"
-EOF
-
-cat >>confdefs.h <<\EOF
-#define PHOSTNAME "/etc/mailname"
-EOF
-
-cat >>confdefs.h <<\EOF
-#define PREFSHELL "/bin/sh"
-EOF
-
-cat >>confdefs.h <<\EOF
-#define PRIVLIB "/usr/share/trn4"
-EOF
-
-cat >>confdefs.h <<\EOF
-#define ROOTID 0
-EOF
-
-cat >>confdefs.h <<\EOF
-#define SCAN /**/
-EOF
-
-cat >>confdefs.h <<\EOF
-#define SCORE /**/
-EOF
-
-cat >>confdefs.h <<\EOF
-#define SELECT_INIT TRUE
-EOF
-
-cat >>confdefs.h <<\EOF
-#define SERVER_NAME "/etc/news/server"
-EOF
-
-cat >>confdefs.h <<\EOF
-#define SUBSCRIPTIONS ""
-EOF
-
-cat >>confdefs.h <<\EOF
-#define SUPPORT_NNTP 1
-EOF
-
-cat >>confdefs.h <<\EOF
-#define SUPPORT_XTHREAD 1
-EOF
-
-cat >>confdefs.h <<\EOF
-#define Signal_t void
-EOF
-
-cat >>confdefs.h <<\EOF
+	cat >>confdefs.h <<\EOF
 #define THREAD_DIR "remote"
 EOF
 
-cat >>confdefs.h <<\EOF
+	THREAD_DIR=""remote""
+
+	cat >>confdefs.h <<\EOF
+#define OVERVIEW_DIR "remote"
+EOF
+
+	OVERVIEW_DIR=""remote""
+
+	cat >>confdefs.h <<\EOF
+#define OVERVIEW_FMT "none"
+EOF
+
+	OVERVIEW_FMT=""none""
+
+	cat >>confdefs.h <<\EOF
+#define PASSNAMES 1
+EOF
+
+	PASSNAMES=1
+
+	cat >>confdefs.h <<\EOF
+#define PHOSTCMD "/usr/bin/hostname"
+EOF
+
+	PHOSTCMD=""/usr/bin/hostname""
+
+	cat >>confdefs.h <<\EOF
+#define PHOSTNAME "/etc/mailname"
+EOF
+
+	PHOSTNAME=""/etc/mailname""
+
+	cat >>confdefs.h <<\EOF
+#define PREFSHELL "/bin/sh"
+EOF
+
+	PREFSHELL=""/bin/sh""
+
+	cat >>confdefs.h <<\EOF
+#define ROOTID 0
+EOF
+
+	ROOTID=0
+
+	cat >>confdefs.h <<\EOF
+#define SCAN /**/
+EOF
+
+	cat >>confdefs.h <<\EOF
+#define SCORE /**/
+EOF
+
+	cat >>confdefs.h <<\EOF
+#define SELECT_INIT TRUE
+EOF
+
+	SELECT_INIT=TRUE
+
+	cat >>confdefs.h <<\EOF
+#define SERVER_NAME "/etc/news/server"
+EOF
+
+	SERVER_NAME=""/etc/news/server""
+
+	cat >>confdefs.h <<\EOF
+#define SUBSCRIPTIONS ""
+EOF
+
+	SUBSCRIPTIONS=""""
+
+	cat >>confdefs.h <<\EOF
+#define SUPPORT_NNTP 1
+EOF
+
+	SUPPORT_NNTP=1
+
+	cat >>confdefs.h <<\EOF
+#define SUPPORT_XTHREAD 1
+EOF
+
+	SUPPORT_XTHREAD=1
+
+	cat >>confdefs.h <<\EOF
+#define Signal_t void
+EOF
+
+	Signal_t="void"
+
+	cat >>confdefs.h <<\EOF
+#define THREAD_DIR "remote"
+EOF
+
+	THREAD_DIR=""remote""
+
+	cat >>confdefs.h <<\EOF
 #define THREAD_INIT FALSE
 EOF
 
-cat >>confdefs.h <<\EOF
+	THREAD_INIT=FALSE
+
+	cat >>confdefs.h <<\EOF
 #define USE_GENAUTH 1
 EOF
 
-DEFEDITOR="/usr/bin/editor"
+	USE_GENAUTH=1
+
+	d_inews='define'
+
+	d_ignoreorg='undef'
+
+	d_internet='define'
+
+	d_newsadm='define'
+
+	d_nntp='define'
+
+	d_xdata=''
+
+	d_usemt=''
+
+	citydist='none'
+
+	cntrydist='none'
+
+	contdist='none'
+
+	locdist='none'
+
+	orgdist='none'
+
+	statedist='none'
+
+	multistatedist='none'
+
+	d_passnames='define'
+
+	d_berknames='define'
+
+	d_usgnames='undef'
+
+	d_acttimes='define'
+
+	PORTABLE='undef'
+
+	d_useov=''
+
+	cf_by=$USER
+
+	cf_time=`date`
 
 MAKE_INEWS=""
 
@@ -9873,11 +10045,7 @@ TK_LDFLAGS=
 
 NNTP_FLAGS=
 
-RN_BIN=/usr/lib/trn4
-
-RN_LIB=/usr/share/trn4
-
-INEWS_BIN=/usr/lib/trn4
+INEWS_BIN=$PRIVBIN
 
 NDIR_LIB=
 
@@ -9885,7 +10053,7 @@ JOBS_LIB=
 
 TERM_LIB=
 
-FILEXP_PATH=/usr/share/trn4/filexp
+FILEXP_PATH=$PRIVLIB/filexp
 
 LDFLAGS="-Wl,-z,relro"
 
@@ -9897,19 +10065,15 @@ MANSECT=1
 
 NAMETYPE=bsd
 
-ORGNAME=/etc/news/organization
-
 PAGER=/usr/bin/pager
 
 PGPCOMMAND=pgp
-
-PORTABLE=undef
 
 RNMAILER=/usr/sbin/sendmail
 
 EXTRA_CLEANUP=
 
-ac_config_files="$ac_config_files Makefile Rnmail Speller access.def:access_def.in norm.saver:norm_saver.in mbox.saver:mbox_saver.in makedir filexp"
+ac_config_files="$ac_config_files Makefile Rnmail Speller access.def:access_def.in norm.saver:norm_saver.in mbox.saver:mbox_saver.in makedir filexp Policy.sh:Policy_sh.in"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -9990,7 +10154,7 @@ DEFS=-DHAVE_CONFIG_H
 : "${CONFIG_STATUS=./config.status}"
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:9993: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:10157: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >"$CONFIG_STATUS" <<_ACEOF
 #! $SHELL
@@ -10168,7 +10332,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:10171: error: ambiguous option: $1
+    { { echo "$as_me:10335: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10187,7 +10351,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:10190: error: unrecognized option: $1
+  -*) { { echo "$as_me:10354: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10230,8 +10394,9 @@ do
   "mbox.saver" ) CONFIG_FILES="$CONFIG_FILES mbox.saver:mbox_saver.in" ;;
   "makedir" ) CONFIG_FILES="$CONFIG_FILES makedir" ;;
   "filexp" ) CONFIG_FILES="$CONFIG_FILES filexp" ;;
+  "Policy.sh" ) CONFIG_FILES="$CONFIG_FILES Policy.sh:Policy_sh.in" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:10234: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:10399: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -10364,7 +10529,82 @@ s,@CTAGS@,$CTAGS,;t t
 s,@ETAGS@,$ETAGS,;t t
 s,@MAKE_LOWER_TAGS@,$MAKE_LOWER_TAGS,;t t
 s,@MAKE_UPPER_TAGS@,$MAKE_UPPER_TAGS,;t t
+s,@PRIVBIN@,$PRIVBIN,;t t
+s,@PRIVLIB@,$PRIVLIB,;t t
+s,@ispell_prg@,$ispell_prg,;t t
+s,@ispell_options@,$ispell_options,;t t
+s,@useinews@,$useinews,;t t
+s,@ACTIVE@,$ACTIVE,;t t
+s,@ACTIVE_TIMES@,$ACTIVE_TIMES,;t t
+s,@BERKNAMES@,$BERKNAMES,;t t
+s,@CALL_INEWS@,$CALL_INEWS,;t t
 s,@DEFEDITOR@,$DEFEDITOR,;t t
+s,@Direntry_t@,$Direntry_t,;t t
+s,@EXTRAINEWS@,$EXTRAINEWS,;t t
+s,@GROUPDESC@,$GROUPDESC,;t t
+s,@HASATTRIBUTE@,$HASATTRIBUTE,;t t
+s,@HAVE_LOCAL_SPOOL@,$HAVE_LOCAL_SPOOL,;t t
+s,@HAVE_TERMLIB@,$HAVE_TERMLIB,;t t
+s,@HOSTBITS@,$HOSTBITS,;t t
+s,@INSTALLPREFIX@,$INSTALLPREFIX,;t t
+s,@INTERNET@,$INTERNET,;t t
+s,@I_DIRENT@,$I_DIRENT,;t t
+s,@I_STDLIB@,$I_STDLIB,;t t
+s,@I_STRING@,$I_STRING,;t t
+s,@I_SYS_DIR@,$I_SYS_DIR,;t t
+s,@I_SYS_TIME@,$I_SYS_TIME,;t t
+s,@I_SYS_WAIT@,$I_SYS_WAIT,;t t
+s,@I_TERMIOS@,$I_TERMIOS,;t t
+s,@I_TIME@,$I_TIME,;t t
+s,@I_UNISTD@,$I_UNISTD,;t t
+s,@I_UTIME@,$I_UTIME,;t t
+s,@MAILFILE@,$MAILFILE,;t t
+s,@MAILPOSTER@,$MAILPOSTER,;t t
+s,@MIMECAP@,$MIMECAP,;t t
+s,@NEWSLIB@,$NEWSLIB,;t t
+s,@NEWSPOSTER@,$NEWSPOSTER,;t t
+s,@NEWSSPOOL@,$NEWSSPOOL,;t t
+s,@NEWS_ADMIN@,$NEWS_ADMIN,;t t
+s,@NORMSIG@,$NORMSIG,;t t
+s,@ORGNAME@,$ORGNAME,;t t
+s,@THREAD_DIR@,$THREAD_DIR,;t t
+s,@OVERVIEW_DIR@,$OVERVIEW_DIR,;t t
+s,@OVERVIEW_FMT@,$OVERVIEW_FMT,;t t
+s,@PASSNAMES@,$PASSNAMES,;t t
+s,@PHOSTCMD@,$PHOSTCMD,;t t
+s,@PHOSTNAME@,$PHOSTNAME,;t t
+s,@PREFSHELL@,$PREFSHELL,;t t
+s,@ROOTID@,$ROOTID,;t t
+s,@SELECT_INIT@,$SELECT_INIT,;t t
+s,@SERVER_NAME@,$SERVER_NAME,;t t
+s,@SUBSCRIPTIONS@,$SUBSCRIPTIONS,;t t
+s,@SUPPORT_NNTP@,$SUPPORT_NNTP,;t t
+s,@SUPPORT_XTHREAD@,$SUPPORT_XTHREAD,;t t
+s,@Signal_t@,$Signal_t,;t t
+s,@THREAD_INIT@,$THREAD_INIT,;t t
+s,@USE_GENAUTH@,$USE_GENAUTH,;t t
+s,@d_inews@,$d_inews,;t t
+s,@d_ignoreorg@,$d_ignoreorg,;t t
+s,@d_internet@,$d_internet,;t t
+s,@d_newsadm@,$d_newsadm,;t t
+s,@d_nntp@,$d_nntp,;t t
+s,@d_xdata@,$d_xdata,;t t
+s,@d_usemt@,$d_usemt,;t t
+s,@citydist@,$citydist,;t t
+s,@cntrydist@,$cntrydist,;t t
+s,@contdist@,$contdist,;t t
+s,@locdist@,$locdist,;t t
+s,@orgdist@,$orgdist,;t t
+s,@statedist@,$statedist,;t t
+s,@multistatedist@,$multistatedist,;t t
+s,@d_passnames@,$d_passnames,;t t
+s,@d_berknames@,$d_berknames,;t t
+s,@d_usgnames@,$d_usgnames,;t t
+s,@d_acttimes@,$d_acttimes,;t t
+s,@PORTABLE@,$PORTABLE,;t t
+s,@d_useov@,$d_useov,;t t
+s,@cf_by@,$cf_by,;t t
+s,@cf_time@,$cf_time,;t t
 s,@MAKE_INEWS@,$MAKE_INEWS,;t t
 s,@MAKE_MSDOS@,$MAKE_MSDOS,;t t
 s,@MAKE_NDIR@,$MAKE_NDIR,;t t
@@ -10374,8 +10614,6 @@ s,@TK_INCS@,$TK_INCS,;t t
 s,@TK_LIBS@,$TK_LIBS,;t t
 s,@TK_LDFLAGS@,$TK_LDFLAGS,;t t
 s,@NNTP_FLAGS@,$NNTP_FLAGS,;t t
-s,@RN_BIN@,$RN_BIN,;t t
-s,@RN_LIB@,$RN_LIB,;t t
 s,@INEWS_BIN@,$INEWS_BIN,;t t
 s,@NDIR_LIB@,$NDIR_LIB,;t t
 s,@JOBS_LIB@,$JOBS_LIB,;t t
@@ -10385,10 +10623,8 @@ s,@LINKFLAGS@,$LINKFLAGS,;t t
 s,@MANDIR@,$MANDIR,;t t
 s,@MANSECT@,$MANSECT,;t t
 s,@NAMETYPE@,$NAMETYPE,;t t
-s,@ORGNAME@,$ORGNAME,;t t
 s,@PAGER@,$PAGER,;t t
 s,@PGPCOMMAND@,$PGPCOMMAND,;t t
-s,@PORTABLE@,$PORTABLE,;t t
 s,@RNMAILER@,$RNMAILER,;t t
 s,@EXTRA_CLEANUP@,$EXTRA_CLEANUP,;t t
 CEOF
@@ -10523,7 +10759,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:10526: creating $ac_file" >&5
+    { echo "$as_me:10762: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -10541,7 +10777,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10544: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10780: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo "$f";;
@@ -10554,7 +10790,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:10557: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10793: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10570,7 +10806,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' "$ac_item"`
         if test -z "$ac_used"; then
-          { echo "$as_me:10573: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:10809: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -10579,7 +10815,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' "$ac_item"`
       if test -n "$ac_seen"; then
-        { echo "$as_me:10582: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:10818: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -10624,7 +10860,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
             ac_init=`$EGREP '[ 	]*'$ac_name'[ 	]*=' "$ac_file"`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'"$ac_file"':,'`
-              { echo "$as_me:10627: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:10863: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -10635,7 +10871,7 @@ $ac_seen" >&2;}
     $EGREP -n '@[A-Z_][A-Z_0-9]+@' "$ac_file" >>"$tmp"/out
     if test -s "$tmp"/out; then
       ac_seen=`sed -e 's,^,'"$ac_file"':,' < "$tmp"/out`
-      { echo "$as_me:10638: WARNING: Some variables may not be substituted:
+      { echo "$as_me:10874: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
@@ -10695,6 +10931,12 @@ then
 	grep -F -v ".SH" dependencies >> Makefile
 fi
  ;;
+    Policy.sh )
+if ! grep "WARNING" Makefile > /dev/null
+then
+	grep -F -v ".SH" dependencies >> Makefile
+fi
+ ;;
   esac
 done
 EOF
@@ -10735,7 +10977,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:10738: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:10980: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -10746,7 +10988,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10749: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10991: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10759,7 +11001,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:10762: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11004: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10878,7 +11120,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
   rm -f "$tmp"/in
   if test x"$ac_file" != x-; then
     if cmp -s "$ac_file" "$tmp/config.h" 2>/dev/null; then
-      { echo "$as_me:10881: $ac_file is unchanged" >&5
+      { echo "$as_me:11123: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
