make template for Rnmail from Rnmail.SH
Signed-off-by: Thomas E. Dickey <dickey@invisible-island.net>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9853,6 +9853,8 @@ cat >>confdefs.h <<\EOF
 #define USE_GENAUTH 1
 EOF
 
+DEFEDITOR="/usr/bin/editor"
+
 MAKE_INEWS=""
 
 MAKE_MSDOS="#"
@@ -9893,9 +9895,21 @@ MANDIR=/usr/share/man/man1
 
 MANSECT=1
 
+NAMETYPE=bsd
+
+ORGNAME=/etc/news/organization
+
+PAGER=/usr/bin/pager
+
+PGPCOMMAND=pgp
+
+PORTABLE=undef
+
+RNMAILER=/usr/sbin/sendmail
+
 EXTRA_CLEANUP=
 
-ac_config_files="$ac_config_files Makefile"
+ac_config_files="$ac_config_files Makefile Rnmail"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -9976,7 +9990,7 @@ DEFS=-DHAVE_CONFIG_H
 : "${CONFIG_STATUS=./config.status}"
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:9979: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:9993: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >"$CONFIG_STATUS" <<_ACEOF
 #! $SHELL
@@ -10154,7 +10168,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:10157: error: ambiguous option: $1
+    { { echo "$as_me:10171: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10173,7 +10187,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:10176: error: unrecognized option: $1
+  -*) { { echo "$as_me:10190: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10209,8 +10223,9 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+  "Rnmail" ) CONFIG_FILES="$CONFIG_FILES Rnmail" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:10213: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:10228: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -10343,6 +10358,7 @@ s,@CTAGS@,$CTAGS,;t t
 s,@ETAGS@,$ETAGS,;t t
 s,@MAKE_LOWER_TAGS@,$MAKE_LOWER_TAGS,;t t
 s,@MAKE_UPPER_TAGS@,$MAKE_UPPER_TAGS,;t t
+s,@DEFEDITOR@,$DEFEDITOR,;t t
 s,@MAKE_INEWS@,$MAKE_INEWS,;t t
 s,@MAKE_MSDOS@,$MAKE_MSDOS,;t t
 s,@MAKE_NDIR@,$MAKE_NDIR,;t t
@@ -10362,6 +10378,12 @@ s,@FILEXP_PATH@,$FILEXP_PATH,;t t
 s,@LINKFLAGS@,$LINKFLAGS,;t t
 s,@MANDIR@,$MANDIR,;t t
 s,@MANSECT@,$MANSECT,;t t
+s,@NAMETYPE@,$NAMETYPE,;t t
+s,@ORGNAME@,$ORGNAME,;t t
+s,@PAGER@,$PAGER,;t t
+s,@PGPCOMMAND@,$PGPCOMMAND,;t t
+s,@PORTABLE@,$PORTABLE,;t t
+s,@RNMAILER@,$RNMAILER,;t t
 s,@EXTRA_CLEANUP@,$EXTRA_CLEANUP,;t t
 CEOF
 
@@ -10495,7 +10517,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:10498: creating $ac_file" >&5
+    { echo "$as_me:10520: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -10513,7 +10535,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10516: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10538: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo "$f";;
@@ -10526,7 +10548,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:10529: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10551: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10542,7 +10564,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' "$ac_item"`
         if test -z "$ac_used"; then
-          { echo "$as_me:10545: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:10567: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -10551,7 +10573,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' "$ac_item"`
       if test -n "$ac_seen"; then
-        { echo "$as_me:10554: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:10576: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -10596,7 +10618,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
             ac_init=`$EGREP '[ 	]*'$ac_name'[ 	]*=' "$ac_file"`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'"$ac_file"':,'`
-              { echo "$as_me:10599: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:10621: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -10607,7 +10629,7 @@ $ac_seen" >&2;}
     $EGREP -n '@[A-Z_][A-Z_0-9]+@' "$ac_file" >>"$tmp"/out
     if test -s "$tmp"/out; then
       ac_seen=`sed -e 's,^,'"$ac_file"':,' < "$tmp"/out`
-      { echo "$as_me:10610: WARNING: Some variables may not be substituted:
+      { echo "$as_me:10632: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
@@ -10620,7 +10642,16 @@ $ac_seen" >&2;}
   # Run the commands associated with the file.
   case "$ac_file" in
     Makefile )
-grep -F -v ".SH" dependencies >> Makefile
+if ! grep "WARNING" Makefile > /dev/null
+then
+	grep -F -v ".SH" dependencies >> Makefile
+fi
+ ;;
+    Rnmail )
+if ! grep "WARNING" Makefile > /dev/null
+then
+	grep -F -v ".SH" dependencies >> Makefile
+fi
  ;;
   esac
 done
@@ -10662,7 +10693,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:10665: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:10696: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -10673,7 +10704,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10676: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10707: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10686,7 +10717,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:10689: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10720: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10805,7 +10836,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
   rm -f "$tmp"/in
   if test x"$ac_file" != x-; then
     if cmp -s "$ac_file" "$tmp/config.h" 2>/dev/null; then
-      { echo "$as_me:10808: $ac_file is unchanged" >&5
+      { echo "$as_me:10839: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
